#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
touch foo.txt
touch bar.txt
git lfs track foo.txt > /dev/null
git lfs track bar.txt > /dev/null
git add foo.txt
git add bar.txt
git add .gitattributes
git commit -m "Initial commit" > /dev/null

popd > /dev/null

git clone origin repo > /dev/null 2>&1

pushd repo > /dev/null
echo "hi" >> foo.txt
echo "bye" >> bar.txt

# Expected LFS-tracked files
echo "foo.txt bar.txt"

popd > /dev/null
