#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "Initial commit" > /dev/null

# Expected common ancestor: 
git rev-parse HEAD

popd > /dev/null

git clone origin repo > /dev/null 2>&1

pushd repo > /dev/null
touch foo.txt
git add foo.txt
# Untracked
touch bar.txt
popd > /dev/null
