#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "Initial commit" > /dev/null

git rev-parse HEAD

popd > /dev/null

git clone origin repo > /dev/null 2>&1

pushd repo > /dev/null
touch included.txt
git add included.txt
mkdir .rwx
touch .rwx/excluded.txt
git add .rwx/excluded.txt
touch untracked.txt
touch .rwx/untracked-excluded.txt
popd > /dev/null
