#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
printf "\0" > foo.bin
git add foo.bin
git commit -m "Initial commit" > /dev/null

# Expected common ancestor: 
git rev-parse HEAD

popd > /dev/null

git clone origin repo > /dev/null 2>&1

pushd repo > /dev/null
printf "\0" >> foo.bin
popd > /dev/null
