#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "Initial commit" > /dev/null

# Expected common ancestor: 
git rev-parse HEAD

popd > /dev/null

git clone origin repo > /dev/null 2>&1
pushd repo > /dev/null


for i in {1..5}; do
  git checkout -b $i > /dev/null 2>&1
  git commit --allow-empty -m "Commit #$i" > /dev/null
done
