#!/bin/bash
set -eou pipefail

# Scenario: Stacked branch where the base branch (origin/feature-1) moved forward
#
#   A -- B (origin/main)
#         \
#          C -- D -- E (origin/feature-1)
#               \
#                F -- G (HEAD, feature-2)
#
# We branched feature-2 from feature-1 at D, but origin/feature-1 moved to E.
# Expected: D

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "A" > /dev/null
git commit --allow-empty -m "B" > /dev/null
git checkout -b feature-1 > /dev/null 2>&1
git commit --allow-empty -m "C" > /dev/null
git commit --allow-empty -m "D" > /dev/null

git rev-parse HEAD

git commit --allow-empty -m "E" > /dev/null
popd > /dev/null

git clone origin repo > /dev/null 2>&1
pushd repo > /dev/null

git checkout feature-1 > /dev/null 2>&1
git checkout HEAD~1 > /dev/null 2>&1
git checkout -b feature-2 > /dev/null 2>&1
git commit --allow-empty -m "F" > /dev/null
git commit --allow-empty -m "G" > /dev/null

git fetch origin > /dev/null 2>&1
