#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "Initial commit" > /dev/null
popd > /dev/null

git clone origin repo > /dev/null 2>&1
pushd repo > /dev/null
MERGE_BASE=$(git rev-parse HEAD)
git commit --allow-empty -m "Diverge" > /dev/null
git checkout $(git rev-parse HEAD) > /dev/null 2>&1

# GetCommit should return the merge-base with origin, not the local-only HEAD
echo "$MERGE_BASE"
