#!/bin/bash
set -eou pipefail

# Scenario: Local commits on main, diverged from origin/main
#
#   A (origin/main)
#    \
#     B (HEAD, main)
#
# Clone, then make a local commit on main.
# Expected: A

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "Initial commit" > /dev/null

git rev-parse HEAD

popd > /dev/null

git clone origin repo > /dev/null 2>&1
pushd repo > /dev/null

git commit --allow-empty -m "Diverge" > /dev/null
