#!/bin/bash
set -eou pipefail

mkdir origin
pushd origin > /dev/null
git init > /dev/null
git commit --allow-empty -m "Initial commit" > /dev/null
popd > /dev/null

git clone origin repo > /dev/null 2>&1
pushd repo > /dev/null
git remote add upstream "upstream-url"

# Expected repo URL
git remote get-url origin
