on:
  cli:
    init:
      ref: ${{ event.git.sha }}

base:
  image: ubuntu:24.04
  config: rwx/base 1.0.0

tasks:
  - key: code
    call: git/clone 2.0.3
    with:
      preserve-git-dir: true
      repository: https://github.com/rwx-cloud/cli.git
      ref: ${{ init.ref }}
      github-token: ${{ github['rwx-cloud'].token }}

  - key: tool-versions
    use: code
    run: |
      while read -r tool version _; do
        printf "%s" "$version" > "$RWX_VALUES/$tool"
      done < .tool-versions
      cp language-server-ref $RWX_VALUES
    filter:
      - .tool-versions
      - language-server-ref

  - key: lsp-code
    call: git/clone 2.0.3
    with:
      repository: https://github.com/rwx-cloud/language-server.git
      ref: ${{ tasks.tool-versions.values.language-server-ref }}
      path: language-server

  - key: lsp-build-def
    use: lsp-code
    run: cp language-server/.rwx/build.yml $RWX_ARTIFACTS/build-run-def

  - key: lsp-build
    call: ${{ tasks.lsp-build-def.artifacts.build-run-def }}
    init:
      ref: ${{ tasks.tool-versions.values.language-server-ref }}

  - key: go
    call: golang/install 1.2.0
    with:
      go-version: ${{ tasks.tool-versions.values.golang }}

  - key: go-deps
    use: [go, code]
    call: golang/mod-download 1.0.0
    filter: [go.mod, go.sum]

  - key: build
    use: [go-deps]
    run: |
      cp ${{ tasks.lsp-build.tasks.build.artifacts.bundle }} internal/lsp/bundle/server.js
      go build -a -ldflags "-w -s -X github.com/rwx-cloud/cli/cmd/rwx/config.Version=${{ init.ref }}" ./cmd/rwx
    outputs:
      artifacts:
        - key: rwx
          path: rwx
